// Data contoh yang tampil pertama kali sebelum ada yang upload file ke Firestore.
// Begitu ada yang upload lewat tombol "Upload data baru", data ini otomatis kegantikan
// oleh data asli di Firestore untuk semua orang yang buka web ini.

export const SEED_RECORDS = [
  {
    "no": 1,
    "nip": "2190007902",
    "nama": "Bani Pamungkas",
    "jabatan": "BM",
    "unit": "KCP Jakarta Masjid Jami Bintaro Jaya",
    "area": "Area Tangerang Selatan",
    "ket": "Resign",
    "tmt": "2026-02-01",
    "kandidat": "DAMARA PUTRI WARDHANA",
    "jabatanFill": "CSR",
    "unitFill": "KC Tangerang BSD ITC",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan FTR Karawaci Kelapa Dua"
  },
  {
    "no": 2,
    "nip": "2170002650",
    "nama": "M. Fakhrurrozi",
    "jabatan": "BM",
    "unit": "KCP Tangerang Karawaci Kelapa Dua",
    "area": "Area Tangerang Selatan",
    "ket": "Pensiun",
    "tmt": "2026-02-01",
    "kandidat": "Fauziyah",
    "jabatanFill": "CSR",
    "unitFill": "KC Tangerang Ciputat",
    "tmtFill": "2026-06-15",
    "ketFill": "Pemenuhan FTR Paramita"
  },
  {
    "no": 3,
    "nip": "2182009522",
    "nama": "Ahmad Taufiq",
    "jabatan": "MRMTL-Caretaker",
    "unit": "KCP Bsd Pasar Modern",
    "area": "Area Tangerang Selatan",
    "ket": "Resign",
    "tmt": "2026-03-01",
    "kandidat": "TSANITA NUR HALIFAH",
    "jabatanFill": "CSR",
    "unitFill": "KCP Tangerang Cirendeu",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS Organik - KLG Terbatas"
  },
  {
    "no": 4,
    "nip": "2185003788",
    "nama": "Aditya Nugraha",
    "jabatan": "CBR",
    "unit": "KCP Serang A Yani 1",
    "area": "Area Banten",
    "ket": "Resign",
    "tmt": "2026-01-12",
    "kandidat": "Asri Humairoh",
    "jabatanFill": "CSR",
    "unitFill": "KCP Cilegon A Yani",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS organik (manning 2)"
  },
  {
    "no": 5,
    "nip": "2192011867",
    "nama": "Angie Riyanti Rinnus",
    "jabatan": "FTR",
    "unit": "KC Cilegon Tirtayasa 1",
    "area": "Area Banten",
    "ket": "PHK",
    "tmt": "2026-03-01",
    "kandidat": "Satiya Rosidah",
    "jabatanFill": "CSR",
    "unitFill": "KCP Tangerang Daan Mogot",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS organik (manning 2)"
  },
  {
    "no": 6,
    "nip": "2180012115",
    "nama": "Chandra Setiawan",
    "jabatan": "MBR",
    "unit": "KCP Tangerang Cikupa 1",
    "area": "Area Banten",
    "ket": "Resign",
    "tmt": "2026-01-31",
    "kandidat": "SITI FARAH AYU FAUZIAH",
    "jabatanFill": "CSR",
    "unitFill": "KC Tangerang Hasyim Ashari",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS prio"
  },
  {
    "no": 7,
    "nip": "2188012797",
    "nama": "Erra Riana",
    "jabatan": "PBR",
    "unit": "Area Banten",
    "area": "Area Banten",
    "ket": "Resign",
    "tmt": "2026-04-30",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 8,
    "nip": "2195017898",
    "nama": "Isti Nanda Putri Lestari",
    "jabatan": "CSR",
    "unit": "KCP Jakarta Kalideres",
    "area": "Area Jakarta Barat",
    "ket": "Meninggal",
    "tmt": "2026-02-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 9,
    "nip": "2183008941",
    "nama": "Krishna Aditya",
    "jabatan": "CBR",
    "unit": "KCP Jakarta Kelapa Dua",
    "area": "Area Jakarta Barat",
    "ket": "Resign",
    "tmt": "2026-04-01",
    "kandidat": "Magdala Nurrahma",
    "jabatanFill": "CSR",
    "unitFill": "KCP Jakarta Kedoya",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS Organik - KLG Terbatas"
  },
  {
    "no": 10,
    "nip": "2186003382",
    "nama": "Retno Hapsari",
    "jabatan": "ISEBDO- Senior",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "ket": "Resign",
    "tmt": "2026-02-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 11,
    "nip": "2191009548",
    "nama": "Lalu Ivan Renbran",
    "jabatan": "ONMS",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "ket": "Jakarta 3",
    "tmt": "2026-02-01",
    "kandidat": "Athallah Alifian Daffa Widjaya",
    "jabatanFill": "CSR",
    "unitFill": "KCP Jakarta Cengkareng",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS organik"
  },
  {
    "no": 12,
    "nip": "2189011538",
    "nama": "Ardhian Bakti Pranata",
    "jabatan": "ROS",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "ket": "Jakarta 3",
    "tmt": "2026-02-01",
    "kandidat": "Muhammad Mahardhika Romadhon",
    "jabatanFill": "CSR",
    "unitFill": "KCP Jakarta Kemanggisan",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS organik"
  },
  {
    "no": 13,
    "nip": "2401021631",
    "nama": "Muhammad Daffa Said Zein",
    "jabatan": "SMERM",
    "unit": "Area Jakarta Thamrin",
    "area": "Area Jakarta Thamrin",
    "ket": "Resign",
    "tmt": "2026-06-06",
    "kandidat": "ALIFFIA KAMILIYAH PUTRI",
    "jabatanFill": "CSR",
    "unitFill": "KCP Jakarta Harco Mangga Dua",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan FTR resign"
  },
  {
    "no": 14,
    "nip": "2184008719",
    "nama": "Yon Aswandi",
    "jabatan": "PSO",
    "unit": "KCP Jakarta Gajah Mada",
    "area": "Area Jakarta Thamrin",
    "ket": "Resign",
    "tmt": "2026-06-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 15,
    "nip": "2191009281",
    "nama": "Mita Hutami Fatmasari",
    "jabatan": "CBR",
    "unit": "KCP Pandeglang 1",
    "area": "Area Banten",
    "ket": "Resign",
    "tmt": "2026-05-30",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 16,
    "nip": "2188018376",
    "nama": "Nidia Susanti",
    "jabatan": "FTR",
    "unit": "KCP Tangerang South City",
    "area": "Area Tangerang Selatan",
    "ket": "Resign",
    "tmt": "2026-06-16",
    "kandidat": "MAULIDA TSAQIFA AZ ZAHRA",
    "jabatanFill": "CSR",
    "unitFill": "KCP Pamulang",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan CS organik"
  },
  {
    "no": 17,
    "nip": "2194014847",
    "nama": "Yesi Guspita Sari",
    "jabatan": "FTR",
    "unit": "KCP Jakarta Harco Mangga Dua",
    "area": "Area Jakarta Thamrin",
    "ket": "Resign",
    "tmt": "2026-08-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 18,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Tangerang Alam Sutera",
    "area": "Area Tangerang Selatan",
    "ket": "Cabang Baru",
    "tmt": "2026-09-01",
    "kandidat": "HAZIZAH AULIA PRATIWI",
    "jabatanFill": "CSR",
    "unitFill": "KCP Tangerang Alam Sutera",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan cabang baru"
  },
  {
    "no": 19,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Tangerang Alam Sutera",
    "area": "Area Tangerang Selatan",
    "ket": "Cabang Baru",
    "tmt": "2026-09-01",
    "kandidat": "SAVNA KHUSNUL KHOTIMAH",
    "jabatanFill": "FTR",
    "unitFill": "KCP Tangerang Graha Raya",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan FTR"
  },
  {
    "no": 20,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Jakarta Roxy",
    "area": "Area Jakarta Thamrin",
    "ket": "Cabang Baru",
    "tmt": "2026-08-01",
    "kandidat": "Nadira Annisa",
    "jabatanFill": "CSR",
    "unitFill": "KCP Jakarta Roxy",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan cabang baru"
  },
  {
    "no": 21,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Jakarta Roxy",
    "area": "Area Jakarta Thamrin",
    "ket": "Cabang Baru",
    "tmt": "2026-08-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 22,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KFF Jakarta Kemenkeu RI Gd. Slamet Sutikno",
    "area": "Area Jakarta Thamrin",
    "ket": "Cabang Baru",
    "tmt": "2026-09-21",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 23,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KFF Jakarta Kemenkeu RI Gd. Slamet Sutikno",
    "area": "Area Jakarta Thamrin",
    "ket": "Cabang Baru",
    "tmt": "2026-09-21",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 24,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Jakarta Slipi",
    "area": "Area Jakarta Barat",
    "ket": "Cabang Baru",
    "tmt": "2026-08-01",
    "kandidat": "Sonia Putri",
    "jabatanFill": "CSR",
    "unitFill": "KCP Jakarta Slipi",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan cabang baru"
  },
  {
    "no": 25,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Tangerang Beringin",
    "area": "Area Banten",
    "ket": "Cabang Baru",
    "tmt": "2026-08-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 26,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Tangerang Beringin",
    "area": "Area Banten",
    "ket": "Cabang Baru",
    "tmt": "2026-08-01",
    "kandidat": "DE'SYA SHALSABILLA",
    "jabatanFill": "CSR",
    "unitFill": "KCP Tangerang Beringin",
    "tmtFill": "2026-08-01",
    "ketFill": "Pemenuhan cabang baru"
  },
  {
    "no": 27,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Jakarta Sangaji",
    "area": "Area Jakarta Thamrin",
    "ket": "Cabang Baru",
    "tmt": null,
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 28,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Jakarta Sangaji",
    "area": "Area Jakarta Thamrin",
    "ket": "Cabang Baru",
    "tmt": null,
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 29,
    "nip": "Cabang Baru",
    "nama": "Cabang Baru",
    "jabatan": "Cabang Baru",
    "unit": "KCP Jakarta Sangaji",
    "area": "Area Jakarta Thamrin",
    "ket": "Cabang Baru",
    "tmt": null,
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 30,
    "nip": "2195014226",
    "nama": "Kabella Ayu Varamedina",
    "jabatan": "CSR",
    "unit": "KCP Cilegon PCI",
    "area": "Area Banten",
    "ket": "Resign",
    "tmt": "2026-08-17",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 31,
    "nip": "2187002317",
    "nama": "Eva Kurniasari",
    "jabatan": "BM",
    "unit": "KCP Bintaro Jaya Xchange",
    "area": "Area Tangerang Selatan",
    "ket": "Resign",
    "tmt": "2026-10-20",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 32,
    "nip": "2198014771",
    "nama": "Dodi Rifo Pramono",
    "jabatan": "MRMTL-Caretaker",
    "unit": "KCP Jakarta Tanjung Duren 1",
    "area": "Area Jakarta Barat",
    "ket": "Resign",
    "tmt": "2026-09-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 33,
    "nip": "2188007893",
    "nama": "Widayanti Wulansari",
    "jabatan": "FTR",
    "unit": "KC Serang",
    "area": "Area Banten",
    "ket": "Resign",
    "tmt": "2026-09-01",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 34,
    "nip": "2184005308",
    "nama": "Chairany Hasanah Ritonga",
    "jabatan": "CBR",
    "unit": "KCP Jakarta Masjid Jami Bintaro Jaya",
    "area": "Area Tangerang Selatan",
    "ket": "Resign",
    "tmt": "2026-09-30",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  },
  {
    "no": 35,
    "nip": "2180010502",
    "nama": "Ali Akbar Putra",
    "jabatan": "MRMTL-Caretaker",
    "unit": "KCP Jakarta Harco Mangga Dua",
    "area": "Area Jakarta Thamrin",
    "ket": "Pensiun",
    "tmt": "2026-12-06",
    "kandidat": NaN,
    "jabatanFill": NaN,
    "unitFill": NaN,
    "tmtFill": null,
    "ketFill": NaN
  }
];

export const SEED_CANDIDATES = [
  {
    "no": 1,
    "nip": "BBT24200100488",
    "nama": "Ratu Tufi Urfiyatul Ula",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP LABUAN",
    "area": "Area Banten",
    "proses": "Sudah Proses",
    "hasil": "Tidak lolos karna umur dan masa kerja",
    "kandidat": "FL"
  },
  {
    "no": 2,
    "nip": "TAD25011113815",
    "nama": "Vira Pingky Lestari",
    "jabatan": "TBR",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 3,
    "nip": "TAD25011112473",
    "nama": "Syifa Bella Kemalia",
    "jabatan": "TBR",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 4,
    "nip": "KRY22202011683",
    "nama": "Cita Maudia ",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG MALABAR",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 5,
    "nip": "BBT24200200722",
    "nama": "Salsabila Fahma Kurnia",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG PARAMITA II BINTARO",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 6,
    "nip": "KRY23200411849",
    "nama": "Davi Akbar Hidayat",
    "jabatan": "BIBIT-Teller",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 7,
    "nip": "BBT25200201413",
    "nama": "Fauziyah",
    "jabatan": "BIBIT - CS",
    "unit": "KC TANGERANG CIPUTAT",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KC Ciputat"
  },
  {
    "no": 8,
    "nip": "BBT23200300158",
    "nama": "Imaniar Suyudi",
    "jabatan": "BIBIT - CS",
    "unit": "KCP TANGERANG CIPUTAT DEWI SARTIKA",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 9,
    "nip": "KRY23200211905",
    "nama": "Litta Oksivia Al Musbon",
    "jabatan": "BIBIT - CS",
    "unit": "KCP JAKARTA BINTARO VETERAN",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 10,
    "nip": "TAD25011101093",
    "nama": "Isrofathul Layli Amalia",
    "jabatan": "RTS",
    "unit": "Area Jakarta Barat",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 11,
    "nip": "BBT24200201198",
    "nama": "Rhiskhi Nandha",
    "jabatan": "BIBIT - CS",
    "unit": "KC TANGERANG CILEDUG",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 12,
    "nip": "KRY22200111387",
    "nama": "Rima Rahmawati",
    "jabatan": "BIBIT - CS",
    "unit": "KCP JAKARTA KALIDERES",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 13,
    "nip": "BBT23200000143",
    "nama": "Elsha Mayang Sari ",
    "jabatan": "BIBIT-Teller",
    "unit": "KC TANGERANG BSD ITC",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 14,
    "nip": "BBT23200400062",
    "nama": "Satrio Cahyo Bijaksono",
    "jabatan": "BIBIT-Teller",
    "unit": "KC TANGERANG BINTARO",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 15,
    "nip": "KRY22200311468",
    "nama": "Sinta Wati",
    "jabatan": "BIBIT - CS",
    "unit": "KCP PAMULANG",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 16,
    "nip": "BBT23200000009\n",
    "nama": "Amalia Ramahwati",
    "jabatan": "BIBIT - CS",
    "unit": "KCP TANGERANG SERUA INDAH",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 17,
    "nip": "TAD25011112470",
    "nama": "Ayu Anis Anasah",
    "jabatan": "TBR",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 18,
    "nip": "BBT24200100759",
    "nama": "Novita Kurniasari",
    "jabatan": "BIBIT-Teller",
    "unit": "KC Area Jakarta Thamrin",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 19,
    "nip": "BBT24200100852",
    "nama": "AZZAHRA SHAFA SALSABILA",
    "jabatan": "BIBIT-Teller",
    "unit": "KC Area Jakarta Thamrin",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 20,
    "nip": "KRY21199911175",
    "nama": "DAMARA PUTRI WARDHANA",
    "jabatan": "BIBIT - CS",
    "unit": "KCP BINTARO JAYA XCHANGE",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KC Tangerang BSD ITC"
  },
  {
    "no": 21,
    "nip": "KRY22200211634",
    "nama": "Muhammad Mahardhika Romadhon",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA KEMANGGISAN",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Kemanggisan"
  },
  {
    "no": 22,
    "nip": "BBT24200200423",
    "nama": "Athallah Alifian Daffa Widjaya",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP Jakarta Cengkareng",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Cengkareng"
  },
  {
    "no": 23,
    "nip": "BBT25200301488",
    "nama": "NERISHA AMIRAH",
    "jabatan": "BIBIT-BO",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 24,
    "nip": "TAD2411255416",
    "nama": "NURI HIDAYATI",
    "jabatan": "BIBIT-BO",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL"
  },
  {
    "no": 25,
    "nip": "TAD2310129933",
    "nama": "ABDUL JABBAR ASSUDAISY",
    "jabatan": "Driver",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "BO"
  },
  {
    "no": 29,
    "nip": "Pemnas",
    "nama": "Naufal Aprianto",
    "jabatan": "Pemnas",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 30,
    "nip": "Pemnas",
    "nama": "Adinda Nurul R",
    "jabatan": "Pemnas",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 31,
    "nip": "BBT CTG",
    "nama": "Rizki Muhammad Shifa",
    "jabatan": "BBT CTG",
    "unit": "CTG",
    "area": "CTG",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan (Sudah di RO 11)",
    "kandidat": "BO"
  },
  {
    "no": 32,
    "nip": "BBT25200302013",
    "nama": "LAUDZAK AKBAR BAIHAQY",
    "jabatan": "BIBIT-BO",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "BO"
  },
  {
    "no": 33,
    "nip": "KRY23200411934",
    "nama": "MUHAMMAD RIZKY DANISWARA",
    "jabatan": "BIBIT-Teller",
    "unit": "KC SERANG",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 34,
    "nip": "Pemnas",
    "nama": "Safirah Hasdi W",
    "jabatan": "Pemnas",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 35,
    "nip": "Pemnas",
    "nama": "Muhammad Rizky Saputra",
    "jabatan": "Pemnas",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 36,
    "nip": "Pemnas",
    "nama": "Asia",
    "jabatan": "Pemnas",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 37,
    "nip": "TAD2411255279",
    "nama": "FAHRUROJI",
    "jabatan": "RSE",
    "unit": "KCP RANGKASBITUNG 1",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 38,
    "nip": "TAD25011112610",
    "nama": "JUMRONI",
    "jabatan": "RSE",
    "unit": "KCP SERANG A YANI 1",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 40,
    "nip": "BBT CTG",
    "nama": "Raffy Revanza Alfarez",
    "jabatan": "BBT CTG",
    "unit": "BBT CTG",
    "area": "CTG",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan (Sudah di RO 11)",
    "kandidat": "BO"
  },
  {
    "no": 41,
    "nip": "BBT CTG",
    "nama": "Winda Nadya",
    "jabatan": "BBT CTG",
    "unit": "BBT CTG",
    "area": "CTG",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 43,
    "nip": "Pemnas",
    "nama": "Azizah Dwi Khairunnisa",
    "jabatan": "Pemnas",
    "unit": "RO IV Jakarta 1",
    "area": "RO IV Jakarta 1",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 44,
    "nip": "TAD24080100766",
    "nama": "GITA EKA PRATIWI",
    "jabatan": "Admin",
    "unit": "Area Banten",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 45,
    "nip": "TAD2411255331",
    "nama": "WINA ANANDA PUTRI",
    "jabatan": "CFE",
    "unit": "KCP TANGERANG VILLA MELATI MAS",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Eksepsi Masa kerja",
    "kandidat": "FL"
  },
  {
    "no": 46,
    "nip": "TAD24080100764",
    "nama": "APRILLIA EKA LESTARI",
    "jabatan": "ACFS",
    "unit": "Area Banten",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (30 Mei 2026)",
    "kandidat": "FL"
  },
  {
    "no": 47,
    "nip": "TAD24040100212",
    "nama": "HAGIES PRATAMA",
    "jabatan": "ACR",
    "unit": "Area Banten",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 48,
    "nip": "BBT25200201740",
    "nama": "Nabilah Anisah Putri Hasbi",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA KEDOYA",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 49,
    "nip": "TAD2102004491",
    "nama": "RATNA HERLINDAH",
    "jabatan": "CSE",
    "unit": "CSE",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 50,
    "nip": "BBT24200200747",
    "nama": "SRI RAHAYU",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA KELAPA DUA",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 51,
    "nip": "BBT23200400307",
    "nama": "SULISTIYA NURUL ZULAIKA",
    "jabatan": "BIBIT-Teller",
    "unit": "KC TANGERANG CILEDUG",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL"
  },
  {
    "no": 52,
    "nip": "TAD2411255269",
    "nama": "TINI OKTAVIANI",
    "jabatan": "CSE",
    "unit": "CSE",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 53,
    "nip": "BBT25200202109",
    "nama": "Yunita Lestari",
    "jabatan": "BIBIT-CS",
    "unit": "KCP JAKARTA TRISAKTI",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL"
  },
  {
    "no": 54,
    "nip": "TAD25011112804",
    "nama": "FINA AMALIA RAHMAN",
    "jabatan": "TBR",
    "unit": "KCP JAKARTA JOGLO",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 55,
    "nip": "BBT25200401758",
    "nama": "QHORI KHOSYARINA",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG BATUCEPER",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 56,
    "nip": "BBT24200100868",
    "nama": "SITI FARAH AYU FAUZIAH",
    "jabatan": "BIBIT-Teller",
    "unit": "KC SERANG",
    "area": "Area Banten",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KC Tangerang Hasyim Ashari"
  },
  {
    "no": 57,
    "nip": "BBT24200200921",
    "nama": "Satiya Rosidah",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP PANDEGLANG 1",
    "area": "Area Banten",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Tangerang Daan Mogot"
  },
  {
    "no": 58,
    "nip": "TAD2411255328",
    "nama": "DZAKY NABHAN AMIN",
    "jabatan": "RSE",
    "unit": "KCP TANGERANG CIPONDOH",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 59,
    "nip": "TAD25011113769",
    "nama": "DINA SUCI ISLAMIYATI",
    "jabatan": "CFE",
    "unit": "CFE",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 60,
    "nip": "TAD25011112635",
    "nama": "Johan Putra Morow",
    "jabatan": "RSE",
    "unit": "KCP TANGERANG SOUTH CITY",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Eksepsi Masa kerja",
    "kandidat": "FL"
  },
  {
    "no": 61,
    "nip": "TAD2210129639",
    "nama": "MIFTAH NUR SAFANAH",
    "jabatan": "RSE",
    "unit": "KCP TANGERANG PARAKAN",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Eksepsi IPK",
    "kandidat": "FL"
  },
  {
    "no": 62,
    "nip": "BBT26200302227",
    "nama": "Shiffa Aida Muhtaromah ",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP RANGKASBITUNG 1",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 63,
    "nip": "TAD25011112456",
    "nama": "FUAD FAJRI NUR SAWALUDIN",
    "jabatan": "RSE",
    "unit": "KC TANGERANG BINTARO",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 64,
    "nip": "TAD25011112475",
    "nama": "NURUL SAIDAH ",
    "jabatan": "CFE",
    "unit": "CFE",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 65,
    "nip": "BBT24200201357",
    "nama": "LULU NABILA ANWAR",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP SERANG KRAGILAN",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 66,
    "nip": "BBT25200201704",
    "nama": "Fadhilah putri nugraha",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP PAMULANG",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 67,
    "nip": "BBT25200302183",
    "nama": "TRIANA MARSANDA HERIN",
    "jabatan": "BBT Teller",
    "unit": "KCP TANGERANG CISOKA",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 68,
    "nip": "TAD2102004860",
    "nama": "AHMAD ROYHAN",
    "jabatan": "CSE",
    "unit": "CSE",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 69,
    "nip": "BBT24200201096",
    "nama": "DEBY SABILA HALFAN",
    "jabatan": "BIBIT-Teller",
    "unit": "KC TANGERANG BINTARO",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 70,
    "nip": "BBT25200302008",
    "nama": "HANIA CAHYA SAKINA",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG GRAHA RAYA",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 71,
    "nip": "TAD25011112595",
    "nama": "Rizki amalia",
    "jabatan": "CFE",
    "unit": "CFE",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 72,
    "nip": "BBT25200202107",
    "nama": "Rufaidah ",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA TANJUNG DUREN 1",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 73,
    "nip": "TAD2102003747",
    "nama": "Haerul Umam",
    "jabatan": "RSE",
    "unit": "KCP CILEGON PCI",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 74,
    "nip": "TAD2102003038",
    "nama": "AGUS RONI",
    "jabatan": "RSE",
    "unit": "KCP CILEGON PCI",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 75,
    "nip": "BBT23200300255",
    "nama": "SITI NURFADILAH APIATI",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP SERANG CIKANDE 1",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 76,
    "nip": "TAD2102008750",
    "nama": "Nabila Yona Amrullah",
    "jabatan": "TBR",
    "unit": "KCP TANGERANG CITY",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 77,
    "nip": "TAD2102008750",
    "nama": "NABILAH YONA AMRULLAH",
    "jabatan": "TBR",
    "unit": "KCP TANGERANG CITY",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 78,
    "nip": "TAD2102003066",
    "nama": "FAUZAN HAKIM",
    "jabatan": "CFE",
    "unit": "CFE",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 79,
    "nip": "TAD2102003129",
    "nama": "MILYUNA HANIFAH",
    "jabatan": "RSE",
    "unit": "KCP TANGERANG CIMONE 1",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 80,
    "nip": "BBT24200400472",
    "nama": "Maulidiyah Istna",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG CIKUPA 1",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 81,
    "nip": "TAD25011112606",
    "nama": "FATIMA ZAHRA WASISTA PUTRI",
    "jabatan": "CSE",
    "unit": "CSE",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 82,
    "nip": "TAD25011112643",
    "nama": "Mohamad Asriyana ",
    "jabatan": "RSE",
    "unit": "KCP LABUAN",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 83,
    "nip": "TAD25011112640",
    "nama": "SARKANI",
    "jabatan": "CFE",
    "unit": "CFE",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 84,
    "nip": "BBT26200302327",
    "nama": "Dhea Salsabila Syifa",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG MALABAR",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 85,
    "nip": "TAD24080100841",
    "nama": "ANDIKO ANGRUGO",
    "jabatan": "CSE",
    "unit": "KCP TANGERANG CITY",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Eksepsi Masa kerja",
    "kandidat": "FL"
  },
  {
    "no": 86,
    "nip": "TAD25011101499",
    "nama": "SRI HANDAYANI",
    "jabatan": "CSE",
    "unit": "CSE",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 87,
    "nip": "TAD25011112948",
    "nama": "ALAN POLANI",
    "jabatan": "TBR",
    "unit": "KC CILEGON TIRTAYASA 1",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 88,
    "nip": "TAD2411255301",
    "nama": "Mira Maulida",
    "jabatan": "RSE",
    "unit": "KCP TANGERANG GRAHA RAYA",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 89,
    "nip": "TAD26011114456",
    "nama": "Ines Almaida",
    "jabatan": "PSR",
    "unit": "KC Area Jakarta Barat",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 90,
    "nip": "TAD2310129917",
    "nama": "MUTIARA OKTAVIANI",
    "jabatan": "CFE",
    "unit": "CFE",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 91,
    "nip": "BBT24200200540",
    "nama": "GHINA KHOLIFAH",
    "jabatan": "BIBIT-Teller",
    "unit": "KFF TANGERANG AL AZHAR BSD",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 92,
    "nip": "TAD25011112534",
    "nama": "Fadil Abdillah",
    "jabatan": "TBR",
    "unit": "KCP TANGERANG PARAMITA II BINTARO",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 93,
    "nip": "TAD2102004713",
    "nama": "AMELIA ARHANI FAUZAN",
    "jabatan": "CSE",
    "unit": "CSE",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak Lolos Tes 1 (6 Juni 2026)",
    "kandidat": "FL"
  },
  {
    "no": 94,
    "nip": "TAD2411255281",
    "nama": "SHABRINA SALSAABILLA",
    "jabatan": "CSE",
    "unit": "CSE",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL"
  },
  {
    "no": 95,
    "nip": "TAD2102001763",
    "nama": "EGI JULIYANTI ANTONI",
    "jabatan": "RTS",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 96,
    "nip": "TAD25011101163",
    "nama": "TENI AGUSTIN ",
    "jabatan": "CFE",
    "unit": "CFE",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 97,
    "nip": "BBT25200402028",
    "nama": "Dewi Rizkiyanti",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG BALARAJA 3",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 98,
    "nip": "BBT26200302288",
    "nama": "Asri Humairoh",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP CILEGON A YANI",
    "area": "Area Banten",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Cilegon A Yani"
  },
  {
    "no": 99,
    "nip": "BBT25200202035",
    "nama": "Lafi Ismatillah",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG PALEM SEMI",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (11 Juli 2026)",
    "kandidat": "FL"
  },
  {
    "no": 100,
    "nip": "BBT25200101388",
    "nama": "MUHAMMAD ADITYA NILMADA AZMI",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG CIRENDEU",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (11 Juli 2026)",
    "kandidat": "FL"
  },
  {
    "no": 101,
    "nip": "BBT25200201603",
    "nama": "TSANITA NUR HALIFAH",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP BSD PASAR MODERN",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Tangerang Cirendeu"
  },
  {
    "no": 102,
    "nip": "BBT25200102051",
    "nama": "Dea Suci Wulandari",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG CIPUTAT DEWI SARTIKA",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 103,
    "nip": "BBT25200301891",
    "nama": "FADHILA MELIYANTI",
    "jabatan": "BIBIT-Teller",
    "unit": "KFF JAKARTA KEMENKEU RI GD. SLAMET SUTIKNO",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 104,
    "nip": "BBT23200211931",
    "nama": "ALIFFIA KAMILIYAH PUTRI",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA HARCO MANGGA DUA",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Jakarta Harco Mangga Dua"
  },
  {
    "no": 105,
    "nip": "KRY22200111477",
    "nama": "Nadira Annisa",
    "jabatan": "BIBIT-CS",
    "unit": "KCP JAKARTA KETAPANG",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Jakarta Roxy"
  },
  {
    "no": 106,
    "nip": "BBT24200300651",
    "nama": "HAZIZAH AULIA PRATIWI",
    "jabatan": "BIBIT-Teller",
    "unit": "KC TANGERANG BSD ITC",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Tangerang Alam Sutera"
  },
  {
    "no": 107,
    "nip": "BBT25200201455",
    "nama": "NANDA UTAMI ZUMMA",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG CIKUPA 1",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (11 Juli 2026)",
    "kandidat": "FL"
  },
  {
    "no": 108,
    "nip": "BBT25200202134",
    "nama": "FINA ANDRIANTI ",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG GRAND BATAVIA",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 109,
    "nip": "BBT24200300592",
    "nama": "LIA AMELIA AGUSTIN",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG CITY",
    "area": "Area Banten",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (11 Juli 2026)",
    "kandidat": "FL"
  },
  {
    "no": 110,
    "nip": "BBT25200001454",
    "nama": "DHIMAS ALFIANTO NUGROHO",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG JATIUWUNG",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 111,
    "nip": "BBT25200102039",
    "nama": "Sonia Putri",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA MERUYA 1",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Jakarta Slipi"
  },
  {
    "no": 112,
    "nip": "KRY23200411837",
    "nama": "MUHAMAD FARREL MAHARDIKA ",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA UNIVERSITAS MERCU BUANA",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (11 Juli 2026)",
    "kandidat": "FL"
  },
  {
    "no": 113,
    "nip": "BBT25200201979",
    "nama": "Sabrina Azzahra",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA ARJUNA",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes 1",
    "hasil": "Tidak lolos tes 1 (11 Juli 2026)",
    "kandidat": "FL"
  },
  {
    "no": 114,
    "nip": "BBT26200302384",
    "nama": "MAULIDA TSAQIFA AZ ZAHRA",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP TANGERANG PARAMITA II BINTARO",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Pamulang"
  },
  {
    "no": 115,
    "nip": "TAD25011113324",
    "nama": "Adi Setiyawan ",
    "jabatan": "JAM",
    "unit": "Area Jakarta Thamrin",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 116,
    "nip": "TAD24081101015",
    "nama": "DE'SYA SHALSABILLA",
    "jabatan": "CFE",
    "unit": "KCP TANGERANG DAAN MOGOT",
    "area": "Area Banten",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Tangerang Beringin"
  },
  {
    "no": 117,
    "nip": "TAD24040100203",
    "nama": "Andhika Musa Faturochman",
    "jabatan": "ACFS",
    "unit": "Area Jakarta Barat",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 118,
    "nip": "TAD25011113821",
    "nama": "SAVNA KHUSNUL KHOTIMAH",
    "jabatan": "TBR",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "FTR - KCP Tangerang Graha Raya"
  },
  {
    "no": 120,
    "nip": "Magang Hub",
    "nama": "Magdala Nurrahma",
    "jabatan": "Magang Hub",
    "unit": "Area Jakarta Barat",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Tes (ALL)",
    "hasil": "LULUS",
    "kandidat": "CS - KCP Jakarta Kedoya"
  },
  {
    "no": 121,
    "nip": "Magang Hub",
    "nama": "Putri Indriani Koeswoyo",
    "jabatan": "Magang Hub",
    "unit": "Area Jakarta Barat",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 122,
    "nip": "Magang Hub",
    "nama": "Ahmad Almayda",
    "jabatan": "Magang Hub",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 123,
    "nip": "Magang hub",
    "nama": "Erlita Mukaromah ",
    "jabatan": "Magang Hub",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 124,
    "nip": "BBT25200301385",
    "nama": "DIAH KOMALASARI",
    "jabatan": "BIBIT TELLER",
    "unit": "KCP CILEGON RS KRAKATAU MEDIKA",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 125,
    "nip": "TAD24080100653",
    "nama": "ABY FADLY MIFTAHULHAQ ",
    "jabatan": "TBR",
    "unit": "Area Tangerang Selatan",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 126,
    "nip": "TAD26011114447",
    "nama": "MUHAMMAD LUTHFI HIBATULLAH AKHIAR ",
    "jabatan": "ACRS",
    "unit": "Area Jakarta Thamrin",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 127,
    "nip": "TAD2411255361",
    "nama": "RICKY LEONALDO",
    "jabatan": "CSE",
    "unit": "KCP TANGERANG KARANG TENGAH",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 128,
    "nip": "BBT25200201393",
    "nama": "SALMA NURAZIZAH",
    "jabatan": "BIBIT-CS",
    "unit": "KCP TANGERANG CIRENDEU",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 129,
    "nip": "BBT25200202004",
    "nama": "FAUZY ACHMAD EMHA",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA GRHA PERTAMINA",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Menunggu MCU",
    "kandidat": "FL"
  },
  {
    "no": 131,
    "nip": "BBT24200101274",
    "nama": "RUSNIA PRATIWI AGUSTIN",
    "jabatan": "BIBIT-Teller",
    "unit": "KCP JAKARTA MUARA KARANG",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Tidak Direkomendasikan",
    "kandidat": NaN
  },
  {
    "no": 132,
    "nip": "BBT25200201889",
    "nama": "IMANUELA ANDINI BRAMANTY",
    "jabatan": "BIBIT-Teller",
    "unit": "KC Area Jakarta Thamrin",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Menunggu MCU",
    "kandidat": "FL"
  },
  {
    "no": 133,
    "nip": "BBT25200201433",
    "nama": "Tiara Bulan Maharani",
    "jabatan": "BIBIT-Teller",
    "unit": "KC Area Jakarta Thamrin",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Tidak lolos tes 1 (8 Agustus 2026)",
    "kandidat": "FL"
  },
  {
    "no": 157,
    "nip": "Talentics",
    "nama": "Khaulah Hafizhotudzikri Muklasin",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 158,
    "nip": "Talentics",
    "nama": "Dita Ginata Mardiana",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 159,
    "nip": "Talentics",
    "nama": "Wardah Islami",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 160,
    "nip": "Talentics",
    "nama": "LAELATUS SA'DIAH AMALIAH",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 161,
    "nip": "Talentics",
    "nama": "rizka",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 162,
    "nip": "Talentics",
    "nama": "Yayah Sunayah",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 163,
    "nip": "Talentics",
    "nama": "Abdul Muhi",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 164,
    "nip": "Talentics",
    "nama": "Aura  Latifatuzzahra",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 165,
    "nip": "Talentics",
    "nama": "Muhammad Rifqi",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 166,
    "nip": "Talentics",
    "nama": "Afnenda Lailatus S",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 167,
    "nip": "Talentics",
    "nama": "Esa Fadillah",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 168,
    "nip": "Talentics",
    "nama": "RAFI RADITYA ZUHRI",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 169,
    "nip": "Talentics",
    "nama": "Venda Fatma Dina",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 170,
    "nip": "Talentics",
    "nama": "Sri Damayanti",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 171,
    "nip": "Talentics",
    "nama": "Muhammad Hanafi",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 172,
    "nip": "Talentics",
    "nama": "Inzhagi Fairuz Zahran",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 173,
    "nip": "Talentics",
    "nama": "Azhar Zahira Ramadhan",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 174,
    "nip": "Talentics",
    "nama": "Desi Fitri Ani",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 175,
    "nip": "Talentics",
    "nama": "Sofiyatun Nisa",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 176,
    "nip": "Talentics",
    "nama": "Uldiana Sari",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 177,
    "nip": "Talentics",
    "nama": "FAYYAZA SHIFA NADIRA",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 178,
    "nip": "Talentics",
    "nama": "Syarifah Syila Alkadrie",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 179,
    "nip": "Talentics",
    "nama": "Nabil Rifqi Zachary Ahsya",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 180,
    "nip": "Talentics",
    "nama": "Mazaya Karamina Kusumah",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 181,
    "nip": "Talentics",
    "nama": "Haifa Istigfari Tauhidienta",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 182,
    "nip": "Talentics",
    "nama": "Eliana Ratmawati",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 183,
    "nip": "Talentics",
    "nama": "Sinta Official",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 184,
    "nip": "Talentics",
    "nama": "Nina Zhafira",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 185,
    "nip": "Talentics",
    "nama": "Azka Darin Pramadani",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 186,
    "nip": "Talentics",
    "nama": "Ikrima Hafizha Cahayani",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 187,
    "nip": "Talentics",
    "nama": "Evie Rusnia",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 188,
    "nip": "Talentics",
    "nama": "Sitti Raudatuljannah",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 189,
    "nip": "Talentics",
    "nama": "NURAVYA NAZYVA",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Tangerang Selatan",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 190,
    "nip": "Talentics",
    "nama": "Shaffa Qanita Nabilah",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 191,
    "nip": "Talentics",
    "nama": "MUHAMAD RIZKI",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 192,
    "nip": "Talentics",
    "nama": "Salma Kamila Putri",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 193,
    "nip": "Talentics",
    "nama": "Audrey Putri",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 194,
    "nip": "Talentics",
    "nama": "Yunita Dewi Lestari",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 195,
    "nip": "Talentics",
    "nama": "May Xenia",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Banten",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 196,
    "nip": "Talentics",
    "nama": "Muhammad Helmy Luthfiansyah",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Barat",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 197,
    "nip": "Talentics",
    "nama": "Mitha Saumi Fitria",
    "jabatan": "Talentics",
    "unit": "Talentics",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 198,
    "nip": "Eksternal",
    "nama": "ZARADIVA TAQIYYAH ZAHRA",
    "jabatan": "Eksternal",
    "unit": "Eksternal",
    "area": "Eksternal",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "FL Organik"
  },
  {
    "no": 199,
    "nip": "TAD2411255250",
    "nama": "Tri Refda Alfian",
    "jabatan": "CSE",
    "unit": "KCP JAKARTA MAHKAMAH AGUNG",
    "area": "Area Jakarta Thamrin",
    "proses": "Sudah Interview",
    "hasil": "Direkomendasikan",
    "kandidat": "Sales Organik"
  },
  {
    "no": 200,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 201,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 202,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 203,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 204,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 205,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 206,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 207,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 208,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 209,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 210,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 211,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 212,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 213,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 214,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 215,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 216,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 217,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 218,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 219,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 220,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 221,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 222,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 223,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 224,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 225,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  },
  {
    "no": 226,
    "nip": "nan",
    "nama": NaN,
    "jabatan": NaN,
    "unit": NaN,
    "area": NaN,
    "proses": NaN,
    "hasil": NaN,
    "kandidat": NaN
  }
];
